@startuml
left to right direction

actor Utilisateur as User
actor Administrateur as Admin

rectangle "Système domotique CasaControl" {
    usecase "Contrôler l'éclairage" as UCE
    usecase "Gérer l'économie d'énergie" as UGE
    usecase "Surveiller la maison" as USM
    usecase "Automatiser des tâches" as UAT
    usecase "Gérer le système" as GS
    usecase "s'authentifier" as SA
    usecase "Installer les infrastructures et les mettre en mode fonctionnel" as IIF
    usecase "Mettre en mode fonctionnel le réseau de communication" as RC
    usecase "Faire une analyse de la consommation d'énergie" as ACE
    usecase "Reconnaître la tâche à automatiser dans le système" as RTA

    (UCE) -right-> (SA) : <<include>>
    (USM) -right-> (SA) : <<include>>
    (UAT) -right-> (SA) : <<include>>
    (GS) -right-> (SA) : <<include>>

    (UCE) .> (ACE) : <<include>>
    (UAT) .> (RTA) : <<include>>
    (UCE) .> (IIF) : <<include>>
    (UGE) .> (IIF) : <<include>>
    (USM) .> (IIF) : <<include>>
    (UAT) .> (IIF) : <<include>>
    (GS) .> (IIF) : <<include>>
    (UCE) .> (RC) : <<include>>
    (UGE) .> (RC) : <<include>>
    (USM) .> (RC) : <<include>>
    (UAT) .> (RC) : <<include>>
    (GS) .> (RC) : <<include>>
}

User --> UCE
User --> UGE : Optimiser la consommation\nDétecter les gaspillages
User --> USM : Surveiller la maison\nDétecter intrusions, fuites, incendies\nRecevoir alertes en cas d'événements anormaux
User -down-> UAT : Contrôler la musique\nOuvrir/Fermer portes et volets\nÀ distance pour les visiteurs autorisés
Admin -left-> GS : Contrôler l'ajout, la modification et la suppression de fonctionnalités

@enduml
